// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - Uptime Monitor</title><link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.ico\"><script src=\"https://cdn.tailwindcss.com\"></script><script>\n\t\t\t\ttailwind.config = {\n\t\t\t\t\ttheme: {\n\t\t\t\t\t\textend: {\n\t\t\t\t\t\t\tcolors: {\n\t\t\t\t\t\t\t\t'glow': {\n\t\t\t\t\t\t\t\t\t50: '#f0f9ff',\n\t\t\t\t\t\t\t\t\t100: '#e0f2fe',\n\t\t\t\t\t\t\t\t\t200: '#bae6fd',\n\t\t\t\t\t\t\t\t\t300: '#7dd3fc',\n\t\t\t\t\t\t\t\t\t400: '#38bdf8',\n\t\t\t\t\t\t\t\t\t500: '#0ea5e9',\n\t\t\t\t\t\t\t\t\t600: '#0284c7',\n\t\t\t\t\t\t\t\t\t700: '#0369a1',\n\t\t\t\t\t\t\t\t\t800: '#075985',\n\t\t\t\t\t\t\t\t\t900: '#0c4a6e',\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t</script><style>\n\t\t\t\t.glow-effect {\n\t\t\t\t\tbox-shadow: 0 0 20px rgba(56, 189, 248, 0.3);\n\t\t\t\t}\n\t\t\t\t.glow-text {\n\t\t\t\t\ttext-shadow: 0 0 10px rgba(56, 189, 248, 0.5);\n\t\t\t\t}\n\t\t\t\t.status-up {\n\t\t\t\t\tcolor: #10b981;\n\t\t\t\t\ttext-shadow: 0 0 10px rgba(16, 185, 129, 0.5);\n\t\t\t\t}\n\t\t\t\t.status-down {\n\t\t\t\t\tcolor: #ef4444;\n\t\t\t\t\ttext-shadow: 0 0 10px rgba(239, 68, 68, 0.5);\n\t\t\t\t}\n\t\t\t\t.status-unknown {\n\t\t\t\t\tcolor: #f59e0b;\n\t\t\t\t\ttext-shadow: 0 0 10px rgba(245, 158, 11, 0.5);\n\t\t\t\t}\n\t\t\t</style></head><body class=\"bg-slate-950 text-white min-h-screen\"><nav class=\"bg-slate-900 border-b border-slate-700\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"flex justify-between h-16\"><div class=\"flex items-center\"><h1 class=\"text-xl font-bold text-blue-400\">Uptime Monitor</h1></div><div class=\"flex items-center space-x-4\"><a href=\"/\" class=\"text-slate-300 hover:text-blue-400 transition-colors\">Dashboard</a></div></div></div></nav><main class=\"max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
