name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        run: echo "Deployment process started"

      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Create SSH private key file
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > homelab_key
          chmod 600 homelab_key

      - name: Deploy and restart service
        env:
          VERSION: ${{ inputs.version }}
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o ProxyCommand="cloudflared access ssh \
              --hostname ${{secrets.SSH_HOST}} \
              --id=${{secrets.CF_ACCESS_CLIENT_ID}} \
              --secret=${{secrets.CF_ACCESS_CLIENT_PASSWORD}}" \
            -i homelab_key \
            ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} << 'EOF'
            'cd /usr/local/bin
            rm -f uptime-monitoring 2>/dev/null
            curl -L "https://github.com/rizface/uptime-monitoring/releases/download/${VERSION}/${VERSION}" -o uptime-monitoring
            sudo chmod 744 /usr/local/bin/uptime-monitoring
            sudo /usr/bin/systemctl restart uptime-monitoring.service
            EOF'
