name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
      - name: Build
        run: go build -o release/${{github.event.release.tag_name}} .
      - name: Upload uptime-monitoring binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GH_TOKEN}}
          tag: ${{ github.event.release.tag_name }}
          file: ./release/${{github.event.release.tag_name}}
          file_glob: true