name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
      - name: Build
        run: go build -o ${{github.event.release.tag_name}} .
      - name: List
        run: ls -l
      - name: List release dir
        run: ls -l ./release
      - name: Upload uptime-monitoring binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{github.event.release.tag_name}}
          file_glob: true